### PR TITLE
chore: Use docker layer cache

### PR DESCRIPTION
**Pull request by kenoss**

### CODE REVIEW

**Comment by kenoss** [comment]
https://github.com/bayard-search/bayard/pull/65 should be merged before this PR and we should add Cargo.lock file.

**Comment by mosuka** [comment]
Thanks!

**Comment by kenoss** [comment]
Ah, it requires modification because #65 solved.  I'll do it.

**Comment by kenoss** [comment]
I noticed that you already did in commit f99996e.  Thanks.

**Pull request merged**
